language: objective-c
osx_image: xcode7.1
install:
- gem install cocoapods
xcode_project: SegueingInfo.xcodeproj
xcode_scheme:
- SegueingInfoiOS
- SegueingInfoOSX
- SegueingInfoExamples
#- "Podspec Lint"