osx_image: xcode611
language: objective-c
script:
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfo -sdk iphonesimulator build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoExampleiOS -sdk iphonesimulator build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoOSX build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoExampleOSX build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoFrameworkiOS -sdk iphonesimulator build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoExampleFrameworkiOS -sdk iphonesimulator build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoFrameworkOSX build test
 - xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoExampleFrameworkOSX build test