language: objective-c

xcode_project: SegueingInfo.xcodeproj
xcode_scheme:
- SegueingInfo
#- SegueingInfoExampleiOS
- SegueingInfoOSX
#- SegueingInfoExampleOSX
- SegueingInfoFrameworkiOS
#- SegueingInfoExampleFrameworkiOS
- SegueingInfoFrameworkOSX
#- SegueingInfoExampleFrameworkOSX
- "Podspec Lint"