language: objective-c

xcode_project: SegueingInfo
xcode_sdk: iphonesimulator8.3
xcode_scheme:
- SegueingInfo
- SegueingInfoExampleiOS
- SegueingInfoOSX
- SegueingInfoExampleOSX
- SegueingInfoFrameworkiOS
- SegueingInfoExampleFrameworkiOS
- SegueingInfoFrameworkOSX
- SegueingInfoExampleFrameworkOSX
- "Podspec Lint"
