language: objective-c
install:
- gem install cocoapods
xcode_project: SegueingInfo.xcodeproj
xcode_scheme:
- SegueingInfo
#- SegueingInfoExampleiOS
- SegueingInfoOSX
#- SegueingInfoExampleOSX
- SegueingInfoFrameworkiOS
#- SegueingInfoExampleFrameworkiOS
- SegueingInfoFrameworkOSX
#- SegueingInfoExampleFrameworkOSX
- "Podspec Lint"