language: objective-c
xcode_project: SegueingInfoExample.xcodeproj
xcode_scheme: SegueingInfoExample
xcode_sdk: iphonesimulator
script: xctool -project SegueingInfoExample.xcodeproj -scheme SegueingInfoExample -sdk iphonesimulator build