language: objective-c
osx_image: xcode7.1

before_install:
- gem install cocoapods
- brew install carthage
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
## make sure the simulator is loaded in time
#- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID

# iOS Framework
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoiOS' -sdk iphonesimulator clean build
# iOS Unit Tests
#- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoiOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' test
# iOS Examples
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoExamples' -sdk iphonesimulator clean build
# iOS UI Tests
#- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoExamples' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' test
# OSX Framework
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoOSX' -sdk macosx clean build
# OSX Unit Tests
#- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoOSX' -sdk macosx test

# Cocoapods
- cd Cocoapods
- pod update
- xcodebuild -workspace SegueingInfoCocoapodsExamples.xcworkspace -scheme 'SegueingInfoCocoapodsExamples' -sdk iphonesimulator clean build
- cd ..

# Carthage iOS
- cd Carthage
- carthage bootstrap --platform iOS --verbose --no-use-binaries --simulator-only
#- xcodebuild -project SegueingInfoCarthageExamples.xcodeproj/ -scheme "SegueingInfoCarthageExamples" -sdk iphonesimulator clean build
#- carthage build --no-skip-current --platform iOS
#- carthage archive SegueingInfo --platform iOS --output SegueingInfo.framework.iOS.zip
- cd ..

# Carthage OSX
- cd Carthage
- carthage bootstrap --platform Mac --verbose --no-use-binaries
#- xcodebuild -project SegueingInfoCarthageExamples.xcodeproj/ -scheme "SegueingInfoCarthageExamples" -sdk macosx clean build
#- carthage build --no-skip-current --platform Mac
#- carthage archive SegueingInfo --platform OSX --output SegueingInfo.framework.OSX.zip
- cd ..
