language: objective-c
osx_image: xcode7.1

before_install:
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoiOS' -sdk iphonesimulator clean build
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoiOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' test
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoExamples' -sdk iphonesimulator clean build
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoExamples' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' test
- xcodebuild -project SegueingInfo.xcodeproj -scheme 'SegueingInfoOSX' -sdk macosx clean build
