language: objective-c
xcode_project: SegueingInfo.xcodeproj
xcode_sdk: iphonesimulator
xcode_scheme:
 - SegueingInfo
 - SegueingInfoExampleiOS
 - SegueingInfoOSX
 - SegueingInfoExampleOSX
 - SegueingInfoFrameworkiOS
 - SegueingInfoExampleFrameworkiOS
 - SegueingInfoFrameworkOSX
 - SegueingInfoExampleFrameworkOSX