language: objective-c
osx_image: xcode7.1

before_install:
- gem install cocoapods

xcode_sdk: iphonesimulator9.1
xcode_project: SegueingInfo.xcodeproj
xcode_scheme:
- SegueingInfoiOS
- SegueingInfoOSX
- SegueingInfoExamples
#- "Podspec Lint"