language: objective-c
xcode_project: SegueingInfo.xcodeproj
xcode_scheme: SegueingInfoExample
xcode_sdk: iphonesimulator
script: xctool -project SegueingInfo.xcodeproj -scheme SegueingInfoExample -sdk iphonesimulator build